### ISSUE TITLE
First card 1/3th of the speed

### ISSUE THREAD

**Issue by coinnodenl** [mbevand/silentarmy#10]
Got this issue with every linux miner, the first card is spinning at 1/3th or 1/4th of the rest, any idea on how to fix this?

**Comment by mifa** [comment]
Looks like your system reserved GPU memory of first card, try to turn on embedded graphics in BIOS and set variables:
GPU_FORCE_64BIT_PTR 0
GPU_MAX_HEAP_SIZE 100
GPU_USE_SYNC_OBJECTS 1
GPU_MAX_ALLOC_PERCENT 100
GPU_SINGLE_ALLOC_PERCENT 100

**Comment by coinnodenl** [comment]
Cheers! Using onboard does the trick, but not booting gnome now.

**Comment by mifa** [comment]
same here on GenethOS

**Comment by coinnodenl** [comment]
No static ip so i have to quess!

**Comment by mbevand** [comment]
Thanks @mifa for helping provide a workaround.
