### ISSUE TITLE
Implement stratum extranonce (+ other fixes)

### ISSUE THREAD

**Issue by nicehashdev** [mbevand/silentarmy#11]
Good job with the miner; some suggestions I may add:

1. I see you set new job immediately after set_target is received; this is not correct, new target is used for every NEXT job that arrives, so you don't need to do anything but just save the new target.

2. You may simply ignore jobs that have clean flag set to false. Some pools regularly send out jobs with clean flag set to false. If you always swap to these new jobs, your mining performance is a little degraded (due to cancelled solution finding). It is completely safe to ignore clean=false jobs, because hashing is so slow process that the miner would never run out of nonce range (nonce range can be restarted with new job).

3. I suggest you to implement extranonce.subscribe. It is an extension of stratum that allows the pool to change server side nonce on miner during the work (and not only initially when subscribed). That way your miner would perform in the best possible way on our service as well (otherwise, miners get reconnected, which is not so good).

What you need to do is following; after you subscribe, send following msg: `{"id":3,"method":"mining.extranonce.subscribe","params":[]}\n`

When you receive following from server:
`{"id":null,"method":"mining.set_extranonce","params":["xxxxxxxxxxxxxxx"]}\n`

xxxxxxxxxxxxxxx represent new server side nonce. You continue to use this new server side nonce with NEXT mining job. Simple as that ;)

**Comment by nerdralph** [comment]
Forget about the extranonce.  The only pool that uses it is nicehash.  They tried pushing it on zogminer too.

**Comment by mbevand** [comment]
1. Thanks I fixed it. https://github.com/mbevand/silentarmy/commit/9b9f84225ae9cf9311bc0c8fb0fcbb83b811d733

2. Good suggestion. Also fixed. https://github.com/mbevand/silentarmy/commit/f6530c6a4c65b2123588d62db42e0893876c2d8f

3. I will think about it... But it seems low priority since @nerdralph said only your pool uses it.

**Comment by mbevand** [comment]
I implemented extranonce: https://github.com/mbevand/silentarmy/commit/47d4497ec7e516259674eb7dbdd4b39cbc95ab32

To use, add /#xnsub to the URL:
`$ silentarmy -c stratum+tcp://host:1234/#xnsub`
