### ISSUE TITLE
"Task exception was never retrieved"

### ISSUE THREAD

**Issue by Deelight-fr** [mbevand/silentarmy#12]
Hi, I just did a checkout of v3 and compiled it.
I have this error when i launch my fresh compiled silentarmy (the bundled binary works fine though)

```
$ ./silentarmy                 
Connecting to us1-zcash.flypool.org:3333            
Stratum server sent us the first job
Mining on 1 device
Total 0.0 sol/s [] 0 shares
Task exception was never retrieved
future: <Task finished coro=<Silentarmy.show_stats() done, defined at ./silentarmy:183> exception=KeyError('0.0',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None) 
  File "./silentarmy", line 228, in show_stats
    rate_gpus = sorted(gpus(last_sols, last_times, period_gpu))
  File "./silentarmy", line 193, in gpus
    sols[devid] = last_sols[0][devid] - last_sols[idx][devid]
KeyError: '0.0'
```

**Comment by osnwt** [comment]
Why it was closed without comment?
I have the same issue. solver itself works in test mode, miner not.

`ubuntu@multiboot:~/mining/silentarmy-3$ ./r
Connecting to zec-eu.coinmine.pl:7007
Stratum server sent us the first job
Mining on 1 device
Total 0.0 sol/s [] 0 shares
Total 0.0 sol/s [] 0 shares
Total 0.0 sol/s [] 0 shares
Task exception was never retrieved
future: <Task finished coro=<Silentarmy.show_stats() done, defined at ./silentarmy:183> exception=KeyError('0.1',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "./silentarmy", line 228, in show_stats
    rate_gpus = sorted(gpus(last_sols, last_times, period_gpu))
  File "./silentarmy", line 193, in gpus
    sols[devid] = last_sols[0][devid] - last_sols[idx][devid]
KeyError: '0.1'
^C
Quitting
ubuntu@multiboot:~/mining/silentarmy-3$ uname -a
Linux multiboot 4.8.0-22-generic #24-Ubuntu SMP Sat Oct 8 09:15:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@multiboot:~/mining/silentarmy-3$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety`

**Comment by Deelight-fr** [comment]
I don't know where I messed up but now the silentarmy python script works fine for me.

Here's the diff between the buggy script and the working one;

`179c179                                                                                                                                                                            <         except socket.gaierror as e:                                                                                                                                             ---                                                                                                                                                                                >         except Exception as e:                                                                                                                                                   193c193,197                                                                                                                                                                        <                 sols[devid] = last_sols[0][devid] - last_sols[idx][devid]                                                                                                        ---                                                                                                                                                                                >                 try:                                                                                                                                                             >                     sols[devid] = last_sols[0][devid] - last_sols[idx][devid]                                                                                                    >                 except KeyError as e:                                                                                                                                            >                     # XXX - ugly fix need to look into why stats are missing                                                                                                     >                     sols[devid] = 0                                                                                                                                              216a221,223                                                                                                                                                                        >             if not self.total_sols:                                                                                                                                              >                 # do not show stats if we don't have any                                                                                                                         >                 continue                                                                                                                                                         249c256,261                                                                                                                                                                        <         asyncio.ensure_future(self.reconnect())                                                                                                                                  ---                                                                                                                                                                                >         try:                                                                                                                                                                     >             asyncio.ensure_future(self.reconnect())                                                                                                                              >         except AttributeError as e:                                                                                                                                              >             fatal(('Error calling ensure_future(): %s\n' % e) +                                                                                                                  >                     'Please update to Python 3.4.5 (or above) - see ' +                                                                                                          >                     'https://github.com/mbevand/silentarmy/issues/8')                                                                                                            445c457                                                                                                                                                                            <                     print("Stratum server returned wrong id: %s" % msg['id'])                                                                                                    ---                                                                                                                                                                                >                     verbose("Stratum server returned wrong id: %s" % msg['id']) `

**Comment by Deelight-fr** [comment]
I don't know where I messed up but now the silentarmy python script works fine for me.

Here's the diff between the buggy script and the working one:
[diff.txt](https://github.com/mbevand/silentarmy/files/571399/diff.txt)

**Comment by osnwt** [comment]
Thanks, it resolved the issue for me.

I think it should not be closed since I had the same issue with 3.0 release as well as git cloned copy.

**Comment by osnwt** [comment]
And yes, github somehow messed up with code tags for me either.

**Comment by mbevand** [comment]
The release tagged v3 is prone to this KeyError bug. But I fixed it in the repo in a later commit (https://github.com/mbevand/silentarmy/commit/c6851571e159e9aa952c76dbeb5bca9890a51e30). So I think we can close this issue.
