### ISSUE TITLE
libsodium-dev on Ubuntu 14.04

### ISSUE THREAD

**Issue by nerdralph** [mbevand/silentarmy#14]
It's not a standard package, so it has to be built from source or use a PPA like http://ppa.launchpad.net/chris-lea/libsodium/ubuntu/

**Comment by mbevand** [comment]
Sorry guys for breaking so many things on Ubuntu 14.04. I want to make SILENTARMY easy to compile & run on this OS version. I'll look into removing the libsodium-dev dependency, next week.

**Comment by asluchevskiy** [comment]
There are no problems running it on 14.04 using this way: #8

**Comment by mbevand** [comment]
Well I wanted to drop the libsodium dependency anyway so I did it:
https://github.com/mbevand/silentarmy/commit/15f3e980b9f748221d9f6f3cfe0948261f48670d
