### ISSUE TITLE
Stat Parser Bug

### ISSUE THREAD

**Issue by jstefanop** [mbevand/silentarmy#22]
Hey your stat python code has a bug...seems to be throwing key errors. The miner still works and hashes in the background, just stats no longer display:

`Task exception was never retrieved
future: <Task finished coro=<Silentarmy.show_stats() done, defined at ./silentarmy:183> exception=KeyError('1.0',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "./silentarmy", line 228, in show_stats
    rate_gpus = sorted(gpus(last_sols, last_times, period_gpu))
  File "./silentarmy", line 193, in gpus
    sols[devid] = last_sols[0][devid] - last_sols[idx][devid]
KeyError: '1.0'`

**Comment by mbevand** [comment]
Make sure you get the latest github revision (not v3). This was fixed in https://github.com/mbevand/silentarmy/commit/c6851571e159e9aa952c76dbeb5bca9890a51e30
