### ISSUE TITLE
Nvidia support Cuda 8.0

### ISSUE THREAD

**Issue by montvid** [mbevand/silentarmy#26]
Hi, I installed the newest nvidia drivers with the cuda 8.0 install on ubuntu 16.04 as in:
https://github.com/etherchain-org/nheqminer#linux-ubuntu-1404--1604-build-cuda_tromp

And built your miner and ziog miner with no errors but on both miners during the launch I get the same error. 

./silentarmy
/usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/monika/silentarmy/sa-solver)"
Solver 0.1: unexpected banner "/home/monika/silentarmy/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/monika/silentarmy/sa-solver)"

./silentarmy --list
/home/monika/silentarmy/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/monika/silentarmy/sa-solver)
Devices on platform "NVIDIA CUDA":
  ID 0: GeForce GT 740M

Maybe you can add support more easy when you see how nheqminer did it. Too bad that miner is a bit slow 2.5 sol on 740M, i hope your's is better. Thanks for your work.

**Comment by mbevand** [comment]
Thanks for the report. I am going to close this issue because Nvidia support is already tracked in this other issue: https://github.com/mbevand/silentarmy/issues/6
