### ISSUE TITLE
Bug in instructions 

### ISSUE THREAD

**Issue by NoahSlv** [mbevand/silentarmy#29]
If you follow the instructions for Ubuntu:

1. Fresh install of Ubuntu 16.04.1 (AMD_64 Desktop version)

2. Download and install latest AMDGPU-PRO Driver  (16.40)

3. Add user to video group

On reboot, system will kernel panic every time.

**Comment by mbevand** [comment]
Ouch! Yeah the drivers can be finicky, but it's not an issue with silentarmy. These instructions come from AMD. Try reporting your problem to https://forum.z.cash/t/silentarmy-v3-now-a-full-miner-multi-gpu-stratum/3580/491 and others may help you. In the past I have also found https://community.amd.com/community/devgurus to be useful (AMD employees monitor this forum.)
