### ISSUE TITLE
Cannot get OpenCL platforms! (-1001)

### ISSUE THREAD

**Issue by brizio1971** [mbevand/silentarmy#3]
after the installation, as soon I run ./silentarmy --nonces 100 i get the error:

Solving default all-zero 140-byte header
Cannot get OpenCL platforms! (-1001)

running make I get the error: /usr/lib/libOpenCL.so: until I have run sudo apt install ocl-icd-opencl-dev

thanks

**Comment by mbevand** [comment]
It seems like you installed an ICD but not an actual OpenCL implementation. You need to install the AMDGPU-Pro driver in order to run silentarmy. The driver installs the following packages (and more):

  amdgpu-pro-libopencl-dev
  amdgpu-pro-libopencl1
  amdgpu-pro-opencl-icd
