### ISSUE TITLE
Missing file on extraction

### ISSUE THREAD

**Issue by Untuchabull** [mbevand/silentarmy#33]
I extracted the Silentarmy master folder and ran the make command, but it did not provide the Sa solver file. Here is the cmd line error

echo 'const char *ocl_code = R"_mrb_(' >_kernel.h
cpp input.cl >>_kernel.h
echo ')_mrb_";' >>_kernel.h
gcc  -std=gnu99 -pedantic -Wextra -Wall -ggdb -Wno-deprecated-declarations -Wno-overlength-strings -I"/opt/AMDAPPSDK-3.0/include"  -c -o main.o main.c
gcc  -std=gnu99 -pedantic -Wextra -Wall -ggdb -Wno-deprecated-declarations -Wno-overlength-strings -I"/opt/AMDAPPSDK-3.0/include"  -c -o blake.o blake.c
gcc  -std=gnu99 -pedantic -Wextra -Wall -ggdb -Wno-deprecated-declarations -Wno-overlength-strings -I"/opt/AMDAPPSDK-3.0/include"  -c -o sha256.o sha256.c
gcc -o sa-solver main.o blake.o sha256.o -rdynamic -L"/opt/amdgpu-pro/lib/x86_64-linux-gnu" -lOpenCL
/usr/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status
Makefile:20: recipe for target 'sa-solver' failed
make: *** [sa-solver] Error 1

**Comment by ddctd143** [comment]
@Untuchabull looks like compiler can't find your OpenCL library:

```
/usr/bin/ld: cannot find -lOpenCL
```

**Comment by Untuchabull** [comment]
How do I fix this? :(

**Comment by mbevand** [comment]
Can you find where is the OpenCL lib on your system?:

find / -name "libOpenCL.so*" 2>/dev/null

**Comment by Untuchabull** [comment]
I got this after running that command: /opt/AMDAPPSDK-3.0/lib/x86/libOpenCL.so
/opt/AMDAPPSDK-3.0/lib/x86/libOpenCL.so.1
/opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so
/opt/AMDAPPSDK-3.0/lib/x86_64/sdk/libOpenCL.so
/opt/AMDAPPSDK-3.0/lib/x86_64/sdk/libOpenCL.so.1
/usr/lib/x86_64-linux-gnu/libOpenCL.so.1.0.0
/usr/lib/x86_64-linux-gnu/libOpenCL.so.1
/usr/share/man/man7/libOpenCL.so.7.gz

**Comment by mbevand** [comment]
Compile with this command and it will work:

make LIBOPENCL=/opt/AMDAPPSDK-3.0/lib/x86_64

The reason of your problem is because for some reason the AMDGPU-PRO driver doesn't create a .so file but instead a .so.1 -- however you can just tell it to use the .so installed by AMDAPPSDK

**Comment by Untuchabull** [comment]
ok, I got rid of all the previous files and I am installing everything from scratch again, I will try this shortly, thank you so much!
