### ISSUE TITLE
After installation AMDGPU-PRO Driver...

### ISSUE THREAD

**Issue by tor888** [mbevand/silentarmy#36]
Hello. After install AMDGPU-PRO Driver I cant login in my machine UBUNTU 16.04, need password< my machine password no work.
Auto login no work.
What I can do .HOW FIX THIS ISSUE?

**Comment by mbevand** [comment]
I am not sure how to help. (I run a headless Ubuntu 16.04 that I log into remotely via ssh.) You should ask for help on https://forum.z.cash or on https://community.amd.com/community/support-forums/drivers-software
