### ISSUE TITLE
Crash on 8 GPUs

### ISSUE THREAD

**Issue by raidersan** [mbevand/silentarmy#37]
Had to take a GPU out of my rigs as I get an error starting the miner with 8 as I was doing with my previous zcash-miner. 7 GPU seems to be the limit

**Comment by jtremblaytdst** [comment]
I get the same error dude it's the maximum client of the driver/software. Check the issue https://github.com/mbevand/silentarmy/issues/38.

Zogminer do the same things.

**Comment by mbevand** [comment]
Closing as a duplicate of #38.
