### ISSUE TITLE
crash sa-solver

### ISSUE THREAD

**Issue by MarcusRed** [mbevand/silentarmy#40]
1 gpu. After running for 5 seconds - 1 minute falls 1 of 2 sa-solver.
I noticed that falls if there is memory overclocking frequency (even minimal).

apport.log:
ERROR: apport (pid 1693) Mon Nov 7 01:36:25 2016: called for pid 1689, signal 11, core limit 0
ERROR: apport (pid 1693) Mon Nov 7 01:36:25 2016: executable: /usr/local/silentarmy3/sa-solver (command line "/usr/local/silentarmy3/sa-solver --mining --use 0")
ERROR: apport (pid 1693) Mon Nov 7 01:36:25 2016: executable does not belong to a package, ignoring

kern.log
Nov 7 01:36:25 SrvRig1 kernel: [ 1043.356060] sa-solver[1689]: segfault at 7fff94bcbec0 ip 0000000000403f15 sp 00007fff840d08a0 error 4 in sa-solver[400000+13000]

OS: Ubuntu server 16.04 LTS
Driver: Amdgpu-pro 16.40.5
GPU: Powercolor Rx470 4GB Red Devil

UPD.
Checked on the Ubuntu server 16.10 (kernel 4.8) falls with the same errors.

**Comment by mbevand** [comment]
If you overclock and it fails, it's not a bug with silentarmy, but a hardware issue. Sorry I can't do anything about it!
