### ISSUE TITLE
Maximum number of clients reached

### ISSUE THREAD

**Issue by johiro** [mbevand/silentarmy#42]
Hello. Thank you for developing this great application. Multi-gpu support is awesome.

I am getting the following error, hope you can help me out.

Error from silentarmy:
pipe closed by peer or os.write(pipe, data) raised exception.

Error from solver:
Solver 2.1: unexpected banner "Maximum number of clients reached"
SILENTARMY mining mode ready"

My rig has 4 HD 7990 6GB, which supposedly are 8 cards of 3GB each.
I get this error when I use instances 2, and when I change it to 1 mining starts without problems.
But I guess these cards should work with instances 2 or am I wrong?

BTW, I have executed "./sa-solver --nonces 100" and it runs without problems on each card.

Ubuntu 15.04 with Crimson Driver 15.12

**Comment by mbevand** [comment]
Thanks for the report. We are tracking the issue in #38
