### ISSUE TITLE
AMD Driver Package

### ISSUE THREAD

**Issue by dylib** [mbevand/silentarmy#5]
Would you know if there's an AMD driver package I could use for 2x FirePro D700 on a mac for use with this project? I searched around the AMD site, although since that's a specialized card there don't seem to be any drivers available, thanks!

**Comment by mbevand** [comment]
A FirePro D700 seems to be a rebranded Radeon HD 7970, or built off the same chip at least. It should support OpenCL out of the box: https://support.apple.com/en-us/HT202823

But be aware that no one has ever reported compiling or running silentarmy on Mac OS X. I don't have Apple hardware to test. Plus this GPU is GCN 1st gen which is known to not work at the moment with silentarmy (although I plan to add GCN 1st gen support soon).

**Comment by hmmmph** [comment]
I'll be looking forward to word of the GCN 1st gen support; and thanks for the help info about the Radeon — it's a starting point at the very least.

**Comment by dylib** [comment]
I'll be looking forward to word of the GCN 1st gen support; thanks for the helpful info about the Radeon — it's a starting point at the very least.

**Comment by dylib** [comment]
I'll be looking forward to word of the GCN 1st gen support; thanks for the helpful info about the Radeon — it's a starting point at the very least.

**Comment by mbevand** [comment]
GCN 1st gen support was added in SILENTARMY v2 a few days ago: https://github.com/mbevand/silentarmy/commit/5f68344448385e2aadd1c1f9e6c06d0a2267e7ff

**Comment by justvanbloom** [comment]
I'll do the port to Mac OS X

**Comment by dylib** [comment]
@justvanbloom: Any ETA you might have?
