### ISSUE TITLE
Miner does not work on lower-end AM3 CPUs (Sempron, Athlon)

### ISSUE THREAD

**Issue by gpushack** [mbevand/silentarmy#50]
A lot of miners have 5+ GPU and 6+ GPU AM3 boards (970, 990) chipset boards.  They use Semprons and Althons for these boards.

Using multithreading on 5+ GPU rigs, the system load spikes to over 5, and in some cases to over 10.  This results in reduced hashrate on GPUs (in some cases, hashrate is reduced by 50%). It may be a good idea to optimize the stratum connections that are managed by CPU, or fix whatever is causing the high CPU load.

**Comment by mbevand** [comment]
I significantly reduced CPU usage in https://github.com/mbevand/silentarmy/commit/146b8dc0b6618852e2f322fab51f3ed3739da07a
Try again, I believe your problem has now completely disappeared!
