### ISSUE TITLE
sa-solver won't run from remote command line

### ISSUE THREAD

**Issue by PabloCastellano** [mbevand/silentarmy#51]
Hi.

I want to run silentarmy in a remote computer which I have ssh access.

The problem is if I run `./silentarmy` or `sa-solver` with `--list` or any other parameter, it seems to be waiting for something that never arrives and I have to kill the process or just press Ctrl+C.
This only happens when I'm running the command remotely.

On the other hand, if I don't run the command remotely, that is, by going physically to the computer , logging in through a graphical session and then opening a terminal in the desktop, the command works fine.

I have tried `export DISPLAY=:0` too with no luck.

**Comment by ddobreff** [comment]
Just use ssh...

**Comment by PabloCastellano** [comment]
@ddobreff The issue appears when using ssh indeed

**Comment by mbevand** [comment]
Can you try:
"strace -o logfile ./sa-solver --list"
and send me logfile?

**Comment by PabloCastellano** [comment]
Closing since I have reinstalled everything and it doesn't happen anymore. I was having some issues with the fglrx driver
