### ISSUE TITLE
asyncio:poll timeout

### ISSUE THREAD

**Issue by Singman33** [mbevand/silentarmy#53]
I'm trying to make your program working on my rig, but whatever pool I use, I got the same error :
INFO:asyncio:poll 999.780 ms took 1001.049 ms: timeout

For debug purpose :

> ./silentarmy --debug
Connecting to us1-zcash.flypool.org:3333
DEBUG:asyncio:Get address info us1-zcash.flypool.org:3333, type=<SocketKind.SOCK_STREAM: 1>
DEBUG:asyncio:execute program '/home/eric/sources-gpu/AMD/silentarmy/sa-solver' stdin=<pipe> stdout=stderr=<pipe>
DEBUG:asyncio:process '/home/eric/sources-gpu/AMD/silentarmy/sa-solver' created: pid 4469
DEBUG:asyncio:execute program '/home/eric/sources-gpu/AMD/silentarmy/sa-solver' stdin=<pipe> stdout=stderr=<pipe>
DEBUG:asyncio:process '/home/eric/sources-gpu/AMD/silentarmy/sa-solver' created: pid 4470
DEBUG:asyncio:Write pipe 9 connected: (<_UnixWritePipeTransport fd=9 idle bufsize=0>, <WriteSubprocessPipeProto fd=0 pipe=<_UnixWritePipeTransport fd=9 idle bufsize=0>>)
DEBUG:asyncio:Write pipe 11 connected: (<_UnixWritePipeTransport fd=11 idle bufsize=0>, <WriteSubprocessPipeProto fd=0 pipe=<_UnixWritePipeTransport fd=11 idle bufsize=0>>)
DEBUG:asyncio:Read pipe 10 connected: (<_UnixReadPipeTransport fd=10 polling>, <ReadSubprocessPipeProto fd=1 pipe=<_UnixReadPipeTransport fd=10 polling>>)
DEBUG:asyncio:Read pipe 12 connected: (<_UnixReadPipeTransport fd=12 polling>, <ReadSubprocessPipeProto fd=1 pipe=<_UnixReadPipeTransport fd=12 polling>>)
INFO:asyncio:execute program '/home/eric/sources-gpu/AMD/silentarmy/sa-solver': <_UnixSubprocessTransport pid=4469 running stdin=<_UnixWritePipeTransport fd=9 idle bufsize=0> stdout=<_UnixReadPipeTransport fd=10 polling>>
INFO:asyncio:execute program '/home/eric/sources-gpu/AMD/silentarmy/sa-solver': <_UnixSubprocessTransport pid=4470 running stdin=<_UnixWritePipeTransport fd=11 idle bufsize=0> stdout=<_UnixReadPipeTransport fd=12 polling>>
Solver 0.0: unexpected banner "/home/eric/sources-gpu/AMD/silentarmy/sa-solver: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /home/eric/sources-gpu/AMD/silentarmy/sa-solver)"
Solver 0.1: unexpected banner "/home/eric/sources-gpu/AMD/silentarmy/sa-solver: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /home/eric/sources-gpu/AMD/silentarmy/sa-solver)"
DEBUG:asyncio:poll 973.718 ms took 0.496 ms: 2 events
INFO:asyncio:<_UnixReadPipeTransport fd=10 polling> was closed by peer
INFO:asyncio:<_UnixWritePipeTransport fd=9 idle bufsize=0> was closed by peer
INFO:asyncio:<_UnixReadPipeTransport fd=12 polling> was closed by peer
INFO:asyncio:<_UnixWritePipeTransport fd=11 idle bufsize=0> was closed by peer
DEBUG:asyncio:process 4469 exited with returncode -9
DEBUG:asyncio:process 4470 exited with returncode -9
INFO:asyncio:<_UnixSubprocessTransport pid=4469 running stdin=<_UnixWritePipeTransport closed fd=9 closed> stdout=<_UnixReadPipeTransport closed fd=10 closed>> exited with return code -9
INFO:asyncio:<_UnixSubprocessTransport pid=4470 running stdin=<_UnixWritePipeTransport closed fd=11 closed> stdout=<_UnixReadPipeTransport closed fd=12 closed>> exited with return code -9
DEBUG:asyncio:Getting address info us1-zcash.flypool.org:3333, type=<SocketKind.SOCK_STREAM: 1> took 93.538 ms: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.99.33.207', 3333)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.99.160.185', 3333))]
DEBUG:asyncio:poll 969.593 ms took 63.355 ms: 1 events
DEBUG:asyncio:connect <socket.socket fd=7, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 0)> to ('192.99.33.207', 3333)
DEBUG:asyncio:poll 904.838 ms took 118.574 ms: 1 events
DEBUG:asyncio:<socket.socket fd=7, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.0.14', 48550), raddr=('192.99.33.207', 3333)> connected to us1-zcash.flypool.org:3333: (<_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>, <__main__.StratumClientProtocol object at 0x7fc10c953a20>)
DEBUG:asyncio:poll 783.716 ms took 118.271 ms: 1 events
DEBUG:asyncio:poll 664.939 ms took 119.218 ms: 1 events
DEBUG:asyncio:poll 999.786 ms took 452.297 ms: 1 events
Stratum server sent us the first job
Mining on 1 device
INFO:asyncio:poll 999.780 ms took 1001.049 ms: timeout
INFO:asyncio:poll 999.784 ms took 1001.073 ms: timeout
INFO:asyncio:poll 999.776 ms took 1001.052 ms: timeout
INFO:asyncio:poll 999.767 ms took 1001.053 ms: timeout

**Comment by Singman33** [comment]
Resolved ! My RIG is a mixed of NVidia and AMD cards, and when I'm launching the miner on the AMD card, it take the OpenCL library with Cuda :)

**Comment by Caravaggioby** [comment]
Hi,
How could you overcome this?
