### ISSUE TITLE
solve_equihash() function unexpectedly increments nonce

### ISSUE THREAD

**Issue by honzik666** [mbevand/silentarmy#56]
Hi,

I believe this line: https://github.com/mbevand/silentarmy/blob/2543323e72bd49e4d51828b42c0eab04c5edf408/main.c#L876

is a bug. The problem is that the function would alternate the supplied header which is something not expected by the caller of the function. I am aware that so far this is not a public library. However, a simple case shows that even the sa-solver binary generates sort unexpected solutions. E.g.:
./sa-solver -i 040000000000000000000000000000000000000000000000000000000000000000000000db4d7a85b768123f1dff1d4c4cece70083b2d27e117b4ac2e31d087988a5eac4000000000000000000000000000000000000000000000000000000000000000090041358ffff071f5712000000000000000000000000000000000000000000000000000000000000

This is the header of the very first block from the main zcash chain. However, the solver would calculate solutions for nonce 0x13, not 0x12 (as specified in the header). The amount of CPU time needed to adjust the nonce field is very neglegible and I believe, the functionality to autoincrement it should be removed. Especially, when it's specified as part of the full 140 byte header.

**Comment by mbevand** [comment]
Thanks for the report. I fixed the unexpected incrementation: https://github.com/mbevand/silentarmy/commit/2da8af6bd3526c3f987534134b1198b352976897

I am going to leave the incrementation in solve_equihash() for now (at least I added a func argument to disable it).
