### ISSUE TITLE
sa_solver segfault and decission

### ISSUE THREAD

**Issue by Warpmh** [mbevand/silentarmy#57]
Hi,

After 753 line in main.c need add:

if ( (inputs[i] / 8) >= seen_len ) {
          sols->valid[sol_i] = 0;
          return 0;
        }

Best Regards,
Warp.

**Comment by mbevand** [comment]
Thanks, fixed: https://github.com/mbevand/silentarmy/commit/599c509d554941db81788893430a48b9d4e26816
