### ISSUE TITLE
another 5% speedup

### ISSUE THREAD

**Issue by nerdralph** [mbevand/silentarmy#66]
by increasing the collision data size.

`#define CMULT 4`

change 
`collisionsData[NR_SLOTS*3*64]`
to:
`collisionsData[NR_SLOTS*CMULT*64]`

also change equihash_round to use:
`for (i = 0; i < cnt-1 && thCollNum < NR_SLOTS*CMULT; i++)`

**Comment by mbevand** [comment]
Committed, thanks :) I actually notice a +10% speedup on R9 Nano:
https://github.com/mbevand/silentarmy/commit/b185e2412cb9eecfb329031958b88e84fe042a4a

**Comment by Kubuxu** [comment]
Getting about 72sol/s on stock 1070, two instances.
