### ISSUE TITLE
uneven results between same cards

### ISSUE THREAD

**Issue by nyo16** [mbevand/silentarmy#68]
Hi, 

I have 2 rigs and i have a "strange" behavior from some of my cards  
The first one has 4 x rx480 8GB and with the v5 i have consistent 75-80 sol per card ( pretty awesome )
My second ring has 4 x 390X 8GB and the perf is a bit strange. The first cards they have consistent 100-110 sol but the other 2 have 35-40 sol. Even if i try just the one of those 2 the perf is the same.
Both setups are with ubuntu 16.04 with amdpro driver and latest ver of the miner.
If i switch to ethereum the perf s the same for all the 4 390X.

Any idea how i can debug this?

Cheers

**Comment by sling00** [comment]
amdgpu is buggy on non rx series cards, i would suggest using fglrx on 14.04 and see if your issues go away.

**Comment by nyo16** [comment]
I validated it, with 14.04 i have 100-105 consistent.
