### ISSUE TITLE
Can't connect to mining pool

### ISSUE THREAD

**Issue by ttt1999** [mbevand/silentarmy#73]
I need some help please.
I compiled silentarmy, using Linux ubuntu...

Devices on platform
"NVIDIA CUDA":
ID 0: GeForce GTX 1080

Total 18627
solutions in 313535.8 ms (59.4 Sol/s)

I made a file called start3
./silentarmy --use 0 --instances=2 -c stratum+tcp://zec-us.coinmine.pl:7007 -u user.worker -p x

I tried to connect to both coinmine.pl and flypool
when i try to start the file

~/silentarmy$./start3

I get the message:
bash: ./start3: Permission denied

The file is in my silentarmy folder.  Not sure what the problem is.  
If anybody can help me that would be great.  Thanks!

**Comment by MartinMakowski** [comment]
Hello ttt1999,

Your issue appears to be due to a lack of execute permissions and proper .sh extension formatting on your shell file. 

To fix this issue please run the following commands at the prompt:
mv start3 start3.sh
chmod +x start3.sh
./start3.sh

That should be it. Please let us know if you have any further issues.

Thank you for choosing to point your hashes at ZClassic!

- Marty

**Comment by ttt1999** [comment]
Thanks so much for your help!  I am still having a problem.  Now after entering the commands
mv start3 start3.sh
chmod +x start3.sh
./start3.sh

    it returned:

./start3.sh: line 1: ./silentarmy: Permission denied

Do I need to do something similar with the silentarmy file, or is there a problem with the start file if my directory is named silentarmy?

Thanks!

**Comment by MartinMakowski** [comment]
Yes for any file that gives you a "permission denied" error you can do:
chmod +x silentarmy
or basically
chmod +x filename.extension

Although it's curious why silentarmy would have been compiled without the +x permissions being set (execute allowed).

Good luck!

- Marty

**Comment by ttt1999** [comment]
This is exciting, it's working!!!  I'm mining now and connected to the pool. Thanks for helping me get started
