### ISSUE TITLE
unexpected banner 

### ISSUE THREAD

**Issue by nateomason** [mbevand/silentarmy#74]
Silentarmy was working fine until it also try to add in the other miner  Nicehash Zcash miner which had me install > cuda and now silent army is not working. 
I am getting this error when try to start mining.

$./silentarmy --use 0 -c stratum+tcp://us1-zcash.flypool.org:3333 -u user

Connecting to us1-zcash.flypool.org:3333
Solver 0.0: unexpected banner "/home/nate/silentarmy/sa-solver: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by /home/nate/silentarmy/sa-solver)"
Solver 0.1: unexpected banner "/home/nate/silentarmy/sa-solver: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by /home/nate/silentarmy/sa-solver)"
Stratum server sent us the first job
Mining on 1 device

When I run ./sa-solver --nonces 100 every thing works great.   I just cannot run silentarmy anymore with out getting that error any recommendations?

**Comment by birdie-github** [comment]
I'm not sure why the documentation says to install CUDA but silentarmy works just find if you compile it against the latest released NVIDIA drivers. You'll need to install OpenCL headers (dependant on your distro).

**Comment by ddobreff** [comment]
Error is due to OpenCL repo library and Cuda library mismatch, recompile again using cuda OpenCL lib and headers.

**Comment by nateomason** [comment]
Recompiling worked and everything is up and running again! 

Thanks
