### ISSUE TITLE
Question to the dev!

### ISSUE THREAD

**Issue by maztheman** [mbevand/silentarmy#75]
in the function equihash_round, when NR_ROWS_LOG == 20, the mask is 0 which means all the "first_words" is intialized to 0.  Would this not always cause "isColl" is always be 1?  Is that intended?  Just seems like a very elaborate way of filling up collisionData...

Then again, I have really no idea what this is doing.

**Comment by mbevand** [comment]
Yes isColl is always 1. It is intended. The OpenCL compiler is smart enough to basically optimize out this entire code, the "first_words" array, etc. The code is no faster when removing this logic by hand.
