### ISSUE TITLE
unsupported initializer for address space in kernel_sols

### ISSUE THREAD

**Issue by jramos** [mbevand/silentarmy#84]
With the latest, using AMDGPU-PRO 16.40 on Ubuntu 16.04.

```
$ ./sa-solver --nonces 100 --use 0 -v
Solving default all-zero 140-byte header
Found 2 OpenCL platform(s)
Using GPU device ID 0
Building program
OpenCL build failed (-11). Build log follows:
unsupported initializer for address space in kernel_sols

$ ./sa-solver --list
Devices on platform "Clover":
  ID 0: AMD HAWAII (DRM 3.2.0, LLVM 3.8.0)
  ID 1: AMD HAWAII (DRM 3.2.0, LLVM 3.8.0)
Devices on platform "AMD Accelerated Parallel Processing":
  ID 2: Hawaii
  ID 3: Hawaii
  ID 4: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
```

Oddly, it works fine if I use ID 2. Anybody have any ideas?

**Comment by ddobreff** [comment]
Looks like driver issues( frglx+amdgpu or radeon+amdgpu mix). Since it's hawaii amdgpu-pro supports it. Remove all drivers and opencl packages and install amdgpu-pro from AMD site. If you are using amdgpu FOSS driver "Hawaii" isn't supported well.

**Comment by jramos** [comment]
Thanks, I had an old version of Mesa installed.

```
apt-get remove mesa-*
```
