### ISSUE TITLE
Stratum server returned wrong id

### ISSUE THREAD

**Issue by n1koo** [mbevand/silentarmy#9]
Just started testing the miner. It seems like its doing a good job mining and 0% is rejected but it seems to be outputting roughly 10 of these in a minute: 

`Stratum server returned wrong id: XXX`

I tried out couple pools (nicehash, coinmine) and happened on both of them. Rig consists of 6 AMD GPU's and Ubuntu 14.04 with Python3.5.

AFAICT its just noise

**Comment by mbevand** [comment]
Yeah, just noise. You can ignore these messages.

**Comment by mbevand** [comment]
Now they are only shown in verbose mode
https://github.com/mbevand/silentarmy/commit/be70d35dd14828d14a495bca57b3fbb6f36afd27
