### ISSUE TITLE
why Nvidia Tesla K80 is slow?

### ISSUE THREAD

**Issue by chenqp7** [mbevand/silentarmy#92]
Total 135.1 sol/s [dev0 19.2, dev1 17.8, dev2 17.3, dev3 15.6, dev4 18.2, dev5
13.4, dev6 16.6, dev7 19.5] 169 shares
Total 134.5 sol/s [dev0 18.8, dev1 17.0, dev2 18.1, dev3 16.2, dev4 17.4, dev5
13.6, dev6 16.5, dev7 17.7] 169 shares
Total 135.2 sol/s [dev0 19.0, dev1 16.9, dev2 17.5, dev3 16.2, dev4 16.8, dev5
14.1, dev6 17.0, dev7 18.4] 169 shares

It's only about 20 sol/s each GPU, while the same device on Windows system has about 100 sol/s each. 
Is that because I don't change any setting or don't change some file which is prepared for AMD GPU?

**Comment by mbevand** [comment]
I don't know. Sorry SA is at the moment not supported.
